version: "3.8"

services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /home/infvn/pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile # hoặc Dockerfile.prod nếu tách file
    image: your-registry/facebook-app:latest
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      # các biến khác nếu dùng next-auth, i18n, v.v...
    depends_on:
      - postgres

volumes:
  pgdata_prod:
