version: "3.8"

services:
  postgres:
    image: postgres:17

    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # ✅ expose cổng ra host

  redis: # ⬅️ NEW
    image: redis:7-alpine
    restart: unless-stopped
    command: >
      redis-server --appendonly yes
      ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}}

  web:
    container_name: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
      - redis
    command: npm run dev_v2
