version: "3.8"

services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - /home/infvn/pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: >
      redis-server --appendonly yes
      ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}}
    ports: ["6379:6379"]
    volumes:
      - /home/infvn/docker-data/redis:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: your-registry/facebook-app:latest
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
      - .env.prod
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
      - redis
