INSERT INTO menu (icon, slug, order_index, is_active, parent_id)
VALUES
  ('friends',        '/friends',        1,  true,  NULL),
  ('memories',       '/memories',       2,  true,  NULL),
  ('saved',          '/saved',          3,  true,  NULL),
  ('groups',         '/groups',         4,  true,  NULL),
  ('video',          '/videos',         5,  true,  NULL),
  ('marketplace',    '/marketplace',    6,  true,  NULL),
  ('feed',           '/feed',           7,  true,  NULL),
  ('fundraisers',    '/fundraisers',    8,  true,  NULL),
  ('games',          '/games',          9,  true,  NULL),
  ('orders',         '/orders',        10,  true,  NULL),
  ('dating',         '/dating',        11,  true,  NULL),
  ('ad_activity',    '/ad-activity',   12,  true,  NULL),
  ('messenger',      '/messenger',     13,  true,  NULL),
  ('messenger_kids', '/messenger-kids',14,  true,  NULL),
  ('reels',          '/reels',         15,  true,  NULL),
  ('birthdays',      '/birthdays',     16,  true,  NULL);

INSERT INTO menu_translations (menu_id, locale, name) VALUES
  (1,  'en', 'Friends'),
  (1,  'vi', 'Bạn bè'),
  (2,  'en', 'Memories'),
  (2,  'vi', 'Kỷ niệm'),
  (3,  'en', 'Saved'),
  (3,  'vi', 'Đã lưu'),
  (4,  'en', 'Groups'),
  (4,  'vi', 'Nhóm'),
  (5,  'en', 'Videos'),
  (5,  'vi', 'Video'),
  (6,  'en', 'Marketplace'),
  (6,  'vi', 'Marketplace'),
  (7,  'en', 'Feed'),
  (7,  'vi', 'Bảng feed'),
  (8,  'en', 'Fundraisers'),
  (8,  'vi', 'Chiến dịch gây quỹ'),
  (9,  'en', 'Games'),
  (9,  'vi', 'Chơi game'),
  (10, 'en', 'Orders'),
  (10, 'vi', 'Đơn đặt hàng và thanh toán'),
  (11, 'en', 'Dating'),
  (11, 'vi', 'Hẹn hò'),
  (12, 'en', 'Ad Activity'),
  (12, 'vi', 'Hoạt động gần đây với quảng cáo'),
  (13, 'en', 'Messenger'),
  (13, 'vi', 'Messenger'),
  (14, 'en', 'Messenger Kids'),
  (14, 'vi', 'Messenger Kids'),
  (15, 'en', 'Reels'),
  (15, 'vi', 'Reels'),
  (16, 'en', 'Birthdays'),
  (16, 'vi', 'Sinh nhật');